# Generated by Django 6.0.2 on 2026-02-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('branding', 'Branding & Logos'), ('print', 'Print & Posters'), ('motion', 'Motion Graphics'), ('video', 'Video Editing')], max_length=20)),
                ('thumbnail', models.ImageField(upload_to='portfolio/thumbnails/')),
                ('video_url', models.URLField(blank=True, help_text='Paste YouTube/Vimeo link here')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
